// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: api/stellpulsar/v1/stellpulsar.proto

// StellPulsar 客户端与服务端交互协议。
//
// 协议目标：
// 1. 客户端首次启动时获取所有可用 StellPulsar 服务端实例。
// 2. 客户端按实例优先级和固定哈希选择目标服务端。
// 3. 客户端与目标服务端建立双向流，用于心跳和规则水位同步。
// 4. 客户端请求配额时携带本地规则版本和 checksum，服务端据此校验双方规则是否一致。
// 5. 客户端可以按需获取服务端规则快照，并校验配置中心下发规则与服务端内存规则是否一致。

package stellpulsarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StellPulsarDiscoveryService_ListInstances_FullMethodName = "/stellpulsar.v1.StellPulsarDiscoveryService/ListInstances"
)

// StellPulsarDiscoveryServiceClient is the client API for StellPulsarDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StellPulsarDiscoveryService 提供客户端启动阶段的服务端实例发现能力。
//
// 客户端先调用 ListInstances 获取当前所有可用 StellPulsar 节点，
// 再根据 priority、weight、instance_id 和本地 hash key 固定选择连接目标。
type StellPulsarDiscoveryServiceClient interface {
	// ListInstances 返回所有可被客户端连接的 StellPulsar 服务端实例。
	//
	// 返回结果应按 priority 升序排列，同优先级内再按健康状态、weight 和 instance_id 稳定排序。
	// 客户端需要缓存 instance_revision，并在过期或连接失败时重新拉取实例列表。
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
}

type stellPulsarDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStellPulsarDiscoveryServiceClient(cc grpc.ClientConnInterface) StellPulsarDiscoveryServiceClient {
	return &stellPulsarDiscoveryServiceClient{cc}
}

func (c *stellPulsarDiscoveryServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, StellPulsarDiscoveryService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StellPulsarDiscoveryServiceServer is the server API for StellPulsarDiscoveryService service.
// All implementations must embed UnimplementedStellPulsarDiscoveryServiceServer
// for forward compatibility.
//
// StellPulsarDiscoveryService 提供客户端启动阶段的服务端实例发现能力。
//
// 客户端先调用 ListInstances 获取当前所有可用 StellPulsar 节点，
// 再根据 priority、weight、instance_id 和本地 hash key 固定选择连接目标。
type StellPulsarDiscoveryServiceServer interface {
	// ListInstances 返回所有可被客户端连接的 StellPulsar 服务端实例。
	//
	// 返回结果应按 priority 升序排列，同优先级内再按健康状态、weight 和 instance_id 稳定排序。
	// 客户端需要缓存 instance_revision，并在过期或连接失败时重新拉取实例列表。
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	mustEmbedUnimplementedStellPulsarDiscoveryServiceServer()
}

// UnimplementedStellPulsarDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStellPulsarDiscoveryServiceServer struct{}

func (UnimplementedStellPulsarDiscoveryServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedStellPulsarDiscoveryServiceServer) mustEmbedUnimplementedStellPulsarDiscoveryServiceServer() {
}
func (UnimplementedStellPulsarDiscoveryServiceServer) testEmbeddedByValue() {}

// UnsafeStellPulsarDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StellPulsarDiscoveryServiceServer will
// result in compilation errors.
type UnsafeStellPulsarDiscoveryServiceServer interface {
	mustEmbedUnimplementedStellPulsarDiscoveryServiceServer()
}

func RegisterStellPulsarDiscoveryServiceServer(s grpc.ServiceRegistrar, srv StellPulsarDiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedStellPulsarDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StellPulsarDiscoveryService_ServiceDesc, srv)
}

func _StellPulsarDiscoveryService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellPulsarDiscoveryServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StellPulsarDiscoveryService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellPulsarDiscoveryServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StellPulsarDiscoveryService_ServiceDesc is the grpc.ServiceDesc for StellPulsarDiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StellPulsarDiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stellpulsar.v1.StellPulsarDiscoveryService",
	HandlerType: (*StellPulsarDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstances",
			Handler:    _StellPulsarDiscoveryService_ListInstances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/stellpulsar/v1/stellpulsar.proto",
}

const (
	StellPulsarRuntimeService_OpenSession_FullMethodName          = "/stellpulsar.v1.StellPulsarRuntimeService/OpenSession"
	StellPulsarRuntimeService_AcquireQuota_FullMethodName         = "/stellpulsar.v1.StellPulsarRuntimeService/AcquireQuota"
	StellPulsarRuntimeService_GetRuleSnapshot_FullMethodName      = "/stellpulsar.v1.StellPulsarRuntimeService/GetRuleSnapshot"
	StellPulsarRuntimeService_ValidateRuleSnapshot_FullMethodName = "/stellpulsar.v1.StellPulsarRuntimeService/ValidateRuleSnapshot"
)

// StellPulsarRuntimeServiceClient is the client API for StellPulsarRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StellPulsarRuntimeService 提供分布式限流运行期能力。
//
// OpenSession 用于维护长连接和规则水位同步；
// AcquireQuota 用于实时获取限流配额；
// GetRuleSnapshot 和 ValidateRuleSnapshot 用于排查或修复客户端与服务端规则不一致。
type StellPulsarRuntimeServiceClient interface {
	// OpenSession 建立客户端和单个 StellPulsar 服务端之间的 gRPC 双向流。
	//
	// 客户端应在固定哈希选中目标实例后调用该接口，并在流内发送 hello、heartbeat、rule_digest、ack。
	// 服务端通过该流返回 hello、heartbeat、rule_changed、drain 和 error。
	OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
	// AcquireQuota 根据服务端内存中的限流规则执行配额扣减。
	//
	// 客户端必须携带 rule_revision 和 rule_checksum。
	// 如果客户端规则和服务端规则不一致，服务端优先返回规则状态类 decision，不执行扣减。
	AcquireQuota(ctx context.Context, in *AcquireQuotaRequest, opts ...grpc.CallOption) (*AcquireQuotaResponse, error)
	// GetRuleSnapshot 返回服务端当前内存中的限流规则快照。
	//
	// 客户端一般不在热路径频繁调用该接口，只在规则不一致、启动校验或诊断时使用。
	GetRuleSnapshot(ctx context.Context, in *GetRuleSnapshotRequest, opts ...grpc.CallOption) (*GetRuleSnapshotResponse, error)
	// ValidateRuleSnapshot 校验客户端持有的规则 digest 是否与服务端一致。
	//
	// 该接口只比较 rule_id、revision、checksum、schema_version 等轻量字段，
	// 适合客户端在收到 RULE_CONFLICT、RULE_STALE 或长连接 rule_changed 后快速确认差异。
	ValidateRuleSnapshot(ctx context.Context, in *ValidateRuleSnapshotRequest, opts ...grpc.CallOption) (*ValidateRuleSnapshotResponse, error)
}

type stellPulsarRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStellPulsarRuntimeServiceClient(cc grpc.ClientConnInterface) StellPulsarRuntimeServiceClient {
	return &stellPulsarRuntimeServiceClient{cc}
}

func (c *stellPulsarRuntimeServiceClient) OpenSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StellPulsarRuntimeService_ServiceDesc.Streams[0], StellPulsarRuntimeService_OpenSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StellPulsarRuntimeService_OpenSessionClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

func (c *stellPulsarRuntimeServiceClient) AcquireQuota(ctx context.Context, in *AcquireQuotaRequest, opts ...grpc.CallOption) (*AcquireQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireQuotaResponse)
	err := c.cc.Invoke(ctx, StellPulsarRuntimeService_AcquireQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stellPulsarRuntimeServiceClient) GetRuleSnapshot(ctx context.Context, in *GetRuleSnapshotRequest, opts ...grpc.CallOption) (*GetRuleSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleSnapshotResponse)
	err := c.cc.Invoke(ctx, StellPulsarRuntimeService_GetRuleSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stellPulsarRuntimeServiceClient) ValidateRuleSnapshot(ctx context.Context, in *ValidateRuleSnapshotRequest, opts ...grpc.CallOption) (*ValidateRuleSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRuleSnapshotResponse)
	err := c.cc.Invoke(ctx, StellPulsarRuntimeService_ValidateRuleSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StellPulsarRuntimeServiceServer is the server API for StellPulsarRuntimeService service.
// All implementations must embed UnimplementedStellPulsarRuntimeServiceServer
// for forward compatibility.
//
// StellPulsarRuntimeService 提供分布式限流运行期能力。
//
// OpenSession 用于维护长连接和规则水位同步；
// AcquireQuota 用于实时获取限流配额；
// GetRuleSnapshot 和 ValidateRuleSnapshot 用于排查或修复客户端与服务端规则不一致。
type StellPulsarRuntimeServiceServer interface {
	// OpenSession 建立客户端和单个 StellPulsar 服务端之间的 gRPC 双向流。
	//
	// 客户端应在固定哈希选中目标实例后调用该接口，并在流内发送 hello、heartbeat、rule_digest、ack。
	// 服务端通过该流返回 hello、heartbeat、rule_changed、drain 和 error。
	OpenSession(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	// AcquireQuota 根据服务端内存中的限流规则执行配额扣减。
	//
	// 客户端必须携带 rule_revision 和 rule_checksum。
	// 如果客户端规则和服务端规则不一致，服务端优先返回规则状态类 decision，不执行扣减。
	AcquireQuota(context.Context, *AcquireQuotaRequest) (*AcquireQuotaResponse, error)
	// GetRuleSnapshot 返回服务端当前内存中的限流规则快照。
	//
	// 客户端一般不在热路径频繁调用该接口，只在规则不一致、启动校验或诊断时使用。
	GetRuleSnapshot(context.Context, *GetRuleSnapshotRequest) (*GetRuleSnapshotResponse, error)
	// ValidateRuleSnapshot 校验客户端持有的规则 digest 是否与服务端一致。
	//
	// 该接口只比较 rule_id、revision、checksum、schema_version 等轻量字段，
	// 适合客户端在收到 RULE_CONFLICT、RULE_STALE 或长连接 rule_changed 后快速确认差异。
	ValidateRuleSnapshot(context.Context, *ValidateRuleSnapshotRequest) (*ValidateRuleSnapshotResponse, error)
	mustEmbedUnimplementedStellPulsarRuntimeServiceServer()
}

// UnimplementedStellPulsarRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStellPulsarRuntimeServiceServer struct{}

func (UnimplementedStellPulsarRuntimeServiceServer) OpenSession(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedStellPulsarRuntimeServiceServer) AcquireQuota(context.Context, *AcquireQuotaRequest) (*AcquireQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireQuota not implemented")
}
func (UnimplementedStellPulsarRuntimeServiceServer) GetRuleSnapshot(context.Context, *GetRuleSnapshotRequest) (*GetRuleSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuleSnapshot not implemented")
}
func (UnimplementedStellPulsarRuntimeServiceServer) ValidateRuleSnapshot(context.Context, *ValidateRuleSnapshotRequest) (*ValidateRuleSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRuleSnapshot not implemented")
}
func (UnimplementedStellPulsarRuntimeServiceServer) mustEmbedUnimplementedStellPulsarRuntimeServiceServer() {
}
func (UnimplementedStellPulsarRuntimeServiceServer) testEmbeddedByValue() {}

// UnsafeStellPulsarRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StellPulsarRuntimeServiceServer will
// result in compilation errors.
type UnsafeStellPulsarRuntimeServiceServer interface {
	mustEmbedUnimplementedStellPulsarRuntimeServiceServer()
}

func RegisterStellPulsarRuntimeServiceServer(s grpc.ServiceRegistrar, srv StellPulsarRuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedStellPulsarRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StellPulsarRuntimeService_ServiceDesc, srv)
}

func _StellPulsarRuntimeService_OpenSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StellPulsarRuntimeServiceServer).OpenSession(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StellPulsarRuntimeService_OpenSessionServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

func _StellPulsarRuntimeService_AcquireQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellPulsarRuntimeServiceServer).AcquireQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StellPulsarRuntimeService_AcquireQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellPulsarRuntimeServiceServer).AcquireQuota(ctx, req.(*AcquireQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StellPulsarRuntimeService_GetRuleSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellPulsarRuntimeServiceServer).GetRuleSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StellPulsarRuntimeService_GetRuleSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellPulsarRuntimeServiceServer).GetRuleSnapshot(ctx, req.(*GetRuleSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StellPulsarRuntimeService_ValidateRuleSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRuleSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellPulsarRuntimeServiceServer).ValidateRuleSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StellPulsarRuntimeService_ValidateRuleSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellPulsarRuntimeServiceServer).ValidateRuleSnapshot(ctx, req.(*ValidateRuleSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StellPulsarRuntimeService_ServiceDesc is the grpc.ServiceDesc for StellPulsarRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StellPulsarRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stellpulsar.v1.StellPulsarRuntimeService",
	HandlerType: (*StellPulsarRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireQuota",
			Handler:    _StellPulsarRuntimeService_AcquireQuota_Handler,
		},
		{
			MethodName: "GetRuleSnapshot",
			Handler:    _StellPulsarRuntimeService_GetRuleSnapshot_Handler,
		},
		{
			MethodName: "ValidateRuleSnapshot",
			Handler:    _StellPulsarRuntimeService_ValidateRuleSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenSession",
			Handler:       _StellPulsarRuntimeService_OpenSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/stellpulsar/v1/stellpulsar.proto",
}
