// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: api/stellpulsar/v1/stellpulsar.proto

// StellPulsar 客户端与服务端交互协议。
//
// 协议目标：
// 1. 客户端首次启动时获取所有可用 StellPulsar 服务端实例。
// 2. 客户端按实例优先级和固定哈希选择目标服务端。
// 3. 客户端与目标服务端建立双向流，用于心跳和规则水位同步。
// 4. 客户端请求配额时携带本地规则版本和 checksum，服务端据此校验双方规则是否一致。
// 5. 客户端可以按需获取服务端规则快照，并校验配置中心下发规则与服务端内存规则是否一致。

package stellpulsarv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuotaDecision 是配额判定结果枚举。
type QuotaDecision int32

const (
	// 未指定状态，正常服务端响应不应返回该值。
	QuotaDecision_QUOTA_DECISION_UNSPECIFIED QuotaDecision = 0
	// 配额允许，本次请求已经扣减成功。
	QuotaDecision_QUOTA_DECISION_ALLOWED QuotaDecision = 1
	// 配额拒绝，规则一致但当前窗口剩余配额不足。
	QuotaDecision_QUOTA_DECISION_DENIED QuotaDecision = 2
	// 客户端规则落后于服务端规则。
	// 客户端应尽快从配置中心或服务端快照更新规则。
	QuotaDecision_QUOTA_DECISION_RULE_STALE QuotaDecision = 3
	// 服务端规则落后于客户端规则。
	// 通常表示配置中心已经下发给客户端，但服务端还未 watch 到或增量还未应用。
	QuotaDecision_QUOTA_DECISION_SERVER_RULE_LAG QuotaDecision = 4
	// 客户端和服务端的规则 checksum 不一致。
	// 客户端应调用 ValidateRuleSnapshot 或 GetRuleSnapshot 诊断差异。
	QuotaDecision_QUOTA_DECISION_RULE_CONFLICT QuotaDecision = 5
	// 服务端不存在客户端请求的规则。
	QuotaDecision_QUOTA_DECISION_RULE_NOT_FOUND QuotaDecision = 6
	// 请求参数非法，例如 application_code、rule_id、quota_key、rule_revision 或 rule_checksum 缺失。
	QuotaDecision_QUOTA_DECISION_INVALID_REQUEST QuotaDecision = 7
	// 当前服务端不是该 quota shard 的 owner，本次请求未扣减。
	// 客户端应使用响应中的 owner_instance 重试。
	QuotaDecision_QUOTA_DECISION_NOT_OWNER QuotaDecision = 8
	// quota shard 正在迁移，本次请求未扣减。
	// 客户端应按 retry_after_ms 退避后重试。
	QuotaDecision_QUOTA_DECISION_SHARD_MIGRATING QuotaDecision = 9
)

// Enum value maps for QuotaDecision.
var (
	QuotaDecision_name = map[int32]string{
		0: "QUOTA_DECISION_UNSPECIFIED",
		1: "QUOTA_DECISION_ALLOWED",
		2: "QUOTA_DECISION_DENIED",
		3: "QUOTA_DECISION_RULE_STALE",
		4: "QUOTA_DECISION_SERVER_RULE_LAG",
		5: "QUOTA_DECISION_RULE_CONFLICT",
		6: "QUOTA_DECISION_RULE_NOT_FOUND",
		7: "QUOTA_DECISION_INVALID_REQUEST",
		8: "QUOTA_DECISION_NOT_OWNER",
		9: "QUOTA_DECISION_SHARD_MIGRATING",
	}
	QuotaDecision_value = map[string]int32{
		"QUOTA_DECISION_UNSPECIFIED":     0,
		"QUOTA_DECISION_ALLOWED":         1,
		"QUOTA_DECISION_DENIED":          2,
		"QUOTA_DECISION_RULE_STALE":      3,
		"QUOTA_DECISION_SERVER_RULE_LAG": 4,
		"QUOTA_DECISION_RULE_CONFLICT":   5,
		"QUOTA_DECISION_RULE_NOT_FOUND":  6,
		"QUOTA_DECISION_INVALID_REQUEST": 7,
		"QUOTA_DECISION_NOT_OWNER":       8,
		"QUOTA_DECISION_SHARD_MIGRATING": 9,
	}
)

func (x QuotaDecision) Enum() *QuotaDecision {
	p := new(QuotaDecision)
	*p = x
	return p
}

func (x QuotaDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_api_stellpulsar_v1_stellpulsar_proto_enumTypes[0].Descriptor()
}

func (QuotaDecision) Type() protoreflect.EnumType {
	return &file_api_stellpulsar_v1_stellpulsar_proto_enumTypes[0]
}

func (x QuotaDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuotaDecision.Descriptor instead.
func (QuotaDecision) EnumDescriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{0}
}

// RuleValidationStatus 是规则摘要校验状态枚举。
type RuleValidationStatus int32

const (
	// 未指定状态，正常服务端响应不应返回该值。
	RuleValidationStatus_RULE_VALIDATION_STATUS_UNSPECIFIED RuleValidationStatus = 0
	// 客户端规则 digest 与服务端一致。
	RuleValidationStatus_RULE_VALIDATION_STATUS_MATCHED RuleValidationStatus = 1
	// 客户端规则版本落后于服务端。
	RuleValidationStatus_RULE_VALIDATION_STATUS_CLIENT_STALE RuleValidationStatus = 2
	// 服务端规则版本落后于客户端。
	RuleValidationStatus_RULE_VALIDATION_STATUS_SERVER_STALE RuleValidationStatus = 3
	// 客户端和服务端版本或 checksum 冲突。
	RuleValidationStatus_RULE_VALIDATION_STATUS_CONFLICT RuleValidationStatus = 4
	// 服务端未找到客户端提交的规则。
	RuleValidationStatus_RULE_VALIDATION_STATUS_NOT_FOUND RuleValidationStatus = 5
)

// Enum value maps for RuleValidationStatus.
var (
	RuleValidationStatus_name = map[int32]string{
		0: "RULE_VALIDATION_STATUS_UNSPECIFIED",
		1: "RULE_VALIDATION_STATUS_MATCHED",
		2: "RULE_VALIDATION_STATUS_CLIENT_STALE",
		3: "RULE_VALIDATION_STATUS_SERVER_STALE",
		4: "RULE_VALIDATION_STATUS_CONFLICT",
		5: "RULE_VALIDATION_STATUS_NOT_FOUND",
	}
	RuleValidationStatus_value = map[string]int32{
		"RULE_VALIDATION_STATUS_UNSPECIFIED":  0,
		"RULE_VALIDATION_STATUS_MATCHED":      1,
		"RULE_VALIDATION_STATUS_CLIENT_STALE": 2,
		"RULE_VALIDATION_STATUS_SERVER_STALE": 3,
		"RULE_VALIDATION_STATUS_CONFLICT":     4,
		"RULE_VALIDATION_STATUS_NOT_FOUND":    5,
	}
)

func (x RuleValidationStatus) Enum() *RuleValidationStatus {
	p := new(RuleValidationStatus)
	*p = x
	return p
}

func (x RuleValidationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleValidationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_stellpulsar_v1_stellpulsar_proto_enumTypes[1].Descriptor()
}

func (RuleValidationStatus) Type() protoreflect.EnumType {
	return &file_api_stellpulsar_v1_stellpulsar_proto_enumTypes[1]
}

func (x RuleValidationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleValidationStatus.Descriptor instead.
func (RuleValidationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{1}
}

// ListInstancesRequest 是客户端发现 StellPulsar 服务端实例的请求。
type ListInstancesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace 是注册中心命名空间，例如 default、dev、prod。
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// application_code 是当前业务应用编码，用于服务端按应用做灰度、隔离或标签过滤。
	ApplicationCode string `protobuf:"bytes,2,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// client_id 是客户端进程或 SDK 实例 ID，可参与固定哈希和诊断。
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// supported_protocol_versions 是客户端支持的协议版本列表。
	// 服务端可据此选择兼容版本，当前默认使用 stellpulsar.v1。
	SupportedProtocolVersions []string `protobuf:"bytes,4,rep,name=supported_protocol_versions,json=supportedProtocolVersions,proto3" json:"supported_protocol_versions,omitempty"`
	// labels 是客户端侧的可选标签，例如 region、zone、env、tenant。
	// 服务端可以用它做实例筛选或返回更适合的优先级结果。
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{0}
}

func (x *ListInstancesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListInstancesRequest) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *ListInstancesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListInstancesRequest) GetSupportedProtocolVersions() []string {
	if x != nil {
		return x.SupportedProtocolVersions
	}
	return nil
}

func (x *ListInstancesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ListInstancesResponse 是可用 StellPulsar 服务端实例列表。
type ListInstancesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version 是服务端选择的协议版本。
	ProtocolVersion string `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// instance_revision 是本次实例列表的版本水位，也作为 topology_revision 使用。
	// 客户端必须使用该值参与 owner 计算，并在 AcquireQuotaRequest 中原样携带。
	InstanceRevision string `protobuf:"bytes,2,opt,name=instance_revision,json=instanceRevision,proto3" json:"instance_revision,omitempty"`
	// expires_at_unix_ms 是实例列表缓存过期时间，Unix 毫秒。
	ExpiresAtUnixMs int64 `protobuf:"varint,3,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	// instances 是按优先级排序后的服务端实例列表。
	Instances []*PulsarInstance `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`
	// hash_algorithm 是客户端和服务端共同使用的 owner 计算算法。
	// 首版固定为 rendezvous_hash_v1，客户端必须按该算法计算 quota shard owner。
	HashAlgorithm string `protobuf:"bytes,5,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{1}
}

func (x *ListInstancesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ListInstancesResponse) GetInstanceRevision() string {
	if x != nil {
		return x.InstanceRevision
	}
	return ""
}

func (x *ListInstancesResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *ListInstancesResponse) GetInstances() []*PulsarInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListInstancesResponse) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

// PulsarInstance 描述一个可被客户端连接的 StellPulsar 服务端实例。
type PulsarInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_id 是服务端实例唯一 ID。
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// host 是客户端访问 gRPC 服务的主机名或 IP。
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// port 是客户端访问 gRPC 服务的端口。
	Port int32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// priority 是实例优先级，数值越小优先级越高。
	// 客户端应优先在最高优先级健康实例集合内做固定哈希。
	Priority int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	// weight 是同优先级实例之间的权重。
	// 首版客户端可以只做稳定排序，后续可用于加权一致性哈希。
	Weight int32 `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	// zone 是实例所在可用区、机房或部署区域。
	Zone string `protobuf:"bytes,6,opt,name=zone,proto3" json:"zone,omitempty"`
	// version 是服务端程序版本。
	Version string `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	// rule_revision 是该实例当前已经应用的全局规则水位。
	RuleRevision string `protobuf:"bytes,8,opt,name=rule_revision,json=ruleRevision,proto3" json:"rule_revision,omitempty"`
	// state 是实例状态，例如 UP、DRAINING、DOWN。
	State string `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	// metadata 是扩展元数据，例如 rule_checksum、grpc_host、grpc_port。
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulsarInstance) Reset() {
	*x = PulsarInstance{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulsarInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulsarInstance) ProtoMessage() {}

func (x *PulsarInstance) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulsarInstance.ProtoReflect.Descriptor instead.
func (*PulsarInstance) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{2}
}

func (x *PulsarInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PulsarInstance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PulsarInstance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PulsarInstance) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PulsarInstance) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PulsarInstance) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PulsarInstance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PulsarInstance) GetRuleRevision() string {
	if x != nil {
		return x.RuleRevision
	}
	return ""
}

func (x *PulsarInstance) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PulsarInstance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ClientFrame 是客户端在 OpenSession 双向流中发送的统一帧。
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id 是本次长连接会话 ID，由客户端生成并在同一条流内保持稳定。
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// client_id 是客户端进程或 SDK 实例 ID。
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// application_code 是当前业务应用编码。
	ApplicationCode string `protobuf:"bytes,3,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// payload 是客户端帧载荷。
	// hello 应是流建立后的第一帧；heartbeat、rule_digest、ack 可在会话生命周期内持续发送。
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Heartbeat
	//	*ClientFrame_RuleDigest
	//	*ClientFrame_Ack
	Payload       isClientFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{3}
}

func (x *ClientFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientFrame) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientFrame) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *ClientFrame) GetPayload() isClientFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientFrame) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetHeartbeat() *ClientHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientFrame) GetRuleDigest() *ClientRuleDigest {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_RuleDigest); ok {
			return x.RuleDigest
		}
	}
	return nil
}

func (x *ClientFrame) GetAck() *ClientAck {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isClientFrame_Payload interface {
	isClientFrame_Payload()
}

type ClientFrame_Hello struct {
	// hello 表示客户端会话初始化信息。
	Hello *ClientHello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type ClientFrame_Heartbeat struct {
	// heartbeat 表示客户端心跳。
	Heartbeat *ClientHeartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type ClientFrame_RuleDigest struct {
	// rule_digest 表示客户端当前持有的规则 digest 集合。
	RuleDigest *ClientRuleDigest `protobuf:"bytes,12,opt,name=rule_digest,json=ruleDigest,proto3,oneof"`
}

type ClientFrame_Ack struct {
	// ack 表示客户端对服务端通知的确认。
	Ack *ClientAck `protobuf:"bytes,13,opt,name=ack,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Payload() {}

func (*ClientFrame_Heartbeat) isClientFrame_Payload() {}

func (*ClientFrame_RuleDigest) isClientFrame_Payload() {}

func (*ClientFrame_Ack) isClientFrame_Payload() {}

// ServerFrame 是服务端在 OpenSession 双向流中发送的统一帧。
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id 对应客户端传入的会话 ID。
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// server_instance_id 是当前处理该长连接的服务端实例 ID。
	ServerInstanceId string `protobuf:"bytes,2,opt,name=server_instance_id,json=serverInstanceId,proto3" json:"server_instance_id,omitempty"`
	// payload 是服务端帧载荷。
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerFrame_Hello
	//	*ServerFrame_Heartbeat
	//	*ServerFrame_RuleChanged
	//	*ServerFrame_Drain
	//	*ServerFrame_Error
	Payload       isServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{4}
}

func (x *ServerFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ServerFrame) GetServerInstanceId() string {
	if x != nil {
		return x.ServerInstanceId
	}
	return ""
}

func (x *ServerFrame) GetPayload() isServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerFrame) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerFrame) GetHeartbeat() *ServerHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ServerFrame) GetRuleChanged() *ServerRuleChanged {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_RuleChanged); ok {
			return x.RuleChanged
		}
	}
	return nil
}

func (x *ServerFrame) GetDrain() *ServerDrain {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ServerError {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerFrame_Payload interface {
	isServerFrame_Payload()
}

type ServerFrame_Hello struct {
	// hello 表示服务端接受会话后的初始化响应。
	Hello *ServerHello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type ServerFrame_Heartbeat struct {
	// heartbeat 表示服务端心跳。
	Heartbeat *ServerHeartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type ServerFrame_RuleChanged struct {
	// rule_changed 表示服务端发现客户端规则水位与服务端不一致。
	RuleChanged *ServerRuleChanged `protobuf:"bytes,12,opt,name=rule_changed,json=ruleChanged,proto3,oneof"`
}

type ServerFrame_Drain struct {
	// drain 表示服务端即将下线或希望客户端迁移连接。
	Drain *ServerDrain `protobuf:"bytes,13,opt,name=drain,proto3,oneof"`
}

type ServerFrame_Error struct {
	// error 表示服务端处理客户端帧时发现协议或运行期错误。
	Error *ServerError `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

func (*ServerFrame_Hello) isServerFrame_Payload() {}

func (*ServerFrame_Heartbeat) isServerFrame_Payload() {}

func (*ServerFrame_RuleChanged) isServerFrame_Payload() {}

func (*ServerFrame_Drain) isServerFrame_Payload() {}

func (*ServerFrame_Error) isServerFrame_Payload() {}

// ClientHello 是客户端建立会话时发送的初始化信息。
type ClientHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version 是客户端希望使用的协议版本。
	ProtocolVersion string `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// sdk_version 是客户端 SDK 版本，便于兼容性诊断。
	SdkVersion string `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// application_code 是当前业务应用编码。
	ApplicationCode string `protobuf:"bytes,3,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// client_id 是客户端进程或 SDK 实例 ID。
	ClientId string `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// selected_instance_id 是客户端通过固定哈希选中的服务端实例 ID。
	// 服务端可用它校验客户端是否连接到了预期实例。
	SelectedInstanceId string `protobuf:"bytes,5,opt,name=selected_instance_id,json=selectedInstanceId,proto3" json:"selected_instance_id,omitempty"`
	// rule_digests 是客户端当前已加载的规则摘要集合。
	// 服务端可在 hello 响应阶段直接判断是否需要客户端重新同步规则。
	RuleDigests   []*RuleDigest `protobuf:"bytes,6,rep,name=rule_digests,json=ruleDigests,proto3" json:"rule_digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{5}
}

func (x *ClientHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ClientHello) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ClientHello) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHello) GetSelectedInstanceId() string {
	if x != nil {
		return x.SelectedInstanceId
	}
	return ""
}

func (x *ClientHello) GetRuleDigests() []*RuleDigest {
	if x != nil {
		return x.RuleDigests
	}
	return nil
}

// ServerHello 是服务端接受会话后的初始化响应。
type ServerHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version 是服务端最终确认使用的协议版本。
	ProtocolVersion string `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// server_instance_id 是当前服务端实例 ID。
	ServerInstanceId string `protobuf:"bytes,2,opt,name=server_instance_id,json=serverInstanceId,proto3" json:"server_instance_id,omitempty"`
	// global_rule_revision 是服务端当前全局规则水位。
	GlobalRuleRevision string `protobuf:"bytes,3,opt,name=global_rule_revision,json=globalRuleRevision,proto3" json:"global_rule_revision,omitempty"`
	// rule_digests 是服务端当前应用维度的规则摘要集合。
	RuleDigests []*RuleDigest `protobuf:"bytes,4,rep,name=rule_digests,json=ruleDigests,proto3" json:"rule_digests,omitempty"`
	// heartbeat_interval_ms 是服务端建议客户端发送心跳的间隔，单位毫秒。
	HeartbeatIntervalMs int64 `protobuf:"varint,5,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{6}
}

func (x *ServerHello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ServerHello) GetServerInstanceId() string {
	if x != nil {
		return x.ServerInstanceId
	}
	return ""
}

func (x *ServerHello) GetGlobalRuleRevision() string {
	if x != nil {
		return x.GlobalRuleRevision
	}
	return ""
}

func (x *ServerHello) GetRuleDigests() []*RuleDigest {
	if x != nil {
		return x.RuleDigests
	}
	return nil
}

func (x *ServerHello) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

// ClientHeartbeat 是客户端心跳。
type ClientHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sent_at_unix_ms 是客户端发送心跳的时间，Unix 毫秒。
	SentAtUnixMs int64 `protobuf:"varint,1,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	// last_seen_server_rule_revision 是客户端最近一次看到的服务端规则水位。
	LastSeenServerRuleRevision string `protobuf:"bytes,2,opt,name=last_seen_server_rule_revision,json=lastSeenServerRuleRevision,proto3" json:"last_seen_server_rule_revision,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ClientHeartbeat) Reset() {
	*x = ClientHeartbeat{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHeartbeat) ProtoMessage() {}

func (x *ClientHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHeartbeat.ProtoReflect.Descriptor instead.
func (*ClientHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{7}
}

func (x *ClientHeartbeat) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *ClientHeartbeat) GetLastSeenServerRuleRevision() string {
	if x != nil {
		return x.LastSeenServerRuleRevision
	}
	return ""
}

// ServerHeartbeat 是服务端心跳。
type ServerHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sent_at_unix_ms 是服务端发送心跳的时间，Unix 毫秒。
	SentAtUnixMs int64 `protobuf:"varint,1,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	// global_rule_revision 是服务端当前全局规则水位。
	GlobalRuleRevision string `protobuf:"bytes,2,opt,name=global_rule_revision,json=globalRuleRevision,proto3" json:"global_rule_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerHeartbeat) Reset() {
	*x = ServerHeartbeat{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeat) ProtoMessage() {}

func (x *ServerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeat.ProtoReflect.Descriptor instead.
func (*ServerHeartbeat) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{8}
}

func (x *ServerHeartbeat) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *ServerHeartbeat) GetGlobalRuleRevision() string {
	if x != nil {
		return x.GlobalRuleRevision
	}
	return ""
}

// ClientRuleDigest 是客户端上报的规则摘要集合。
type ClientRuleDigest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rule_digests 是客户端当前持有的规则 digest。
	RuleDigests   []*RuleDigest `protobuf:"bytes,1,rep,name=rule_digests,json=ruleDigests,proto3" json:"rule_digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRuleDigest) Reset() {
	*x = ClientRuleDigest{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRuleDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRuleDigest) ProtoMessage() {}

func (x *ClientRuleDigest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRuleDigest.ProtoReflect.Descriptor instead.
func (*ClientRuleDigest) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{9}
}

func (x *ClientRuleDigest) GetRuleDigests() []*RuleDigest {
	if x != nil {
		return x.RuleDigests
	}
	return nil
}

// ServerRuleChanged 是服务端通知客户端规则发生变化或规则不一致。
type ServerRuleChanged struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// global_rule_revision 是服务端当前全局规则水位。
	GlobalRuleRevision string `protobuf:"bytes,1,opt,name=global_rule_revision,json=globalRuleRevision,proto3" json:"global_rule_revision,omitempty"`
	// changed_rules 是服务端认为需要客户端关注的规则 digest。
	// 其中可能包括服务端已更新、客户端缺失、客户端冲突的规则。
	ChangedRules []*RuleDigest `protobuf:"bytes,2,rep,name=changed_rules,json=changedRules,proto3" json:"changed_rules,omitempty"`
	// requires_client_resync 表示客户端是否需要主动重新同步规则。
	// true 时客户端应优先从配置中心或 GetRuleSnapshot 拉取最新规则。
	RequiresClientResync bool `protobuf:"varint,3,opt,name=requires_client_resync,json=requiresClientResync,proto3" json:"requires_client_resync,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServerRuleChanged) Reset() {
	*x = ServerRuleChanged{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRuleChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRuleChanged) ProtoMessage() {}

func (x *ServerRuleChanged) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRuleChanged.ProtoReflect.Descriptor instead.
func (*ServerRuleChanged) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{10}
}

func (x *ServerRuleChanged) GetGlobalRuleRevision() string {
	if x != nil {
		return x.GlobalRuleRevision
	}
	return ""
}

func (x *ServerRuleChanged) GetChangedRules() []*RuleDigest {
	if x != nil {
		return x.ChangedRules
	}
	return nil
}

func (x *ServerRuleChanged) GetRequiresClientResync() bool {
	if x != nil {
		return x.RequiresClientResync
	}
	return false
}

// ClientAck 是客户端对服务端通知的确认帧。
type ClientAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ack_id 是确认 ID，可对应服务端通知 ID 或客户端自定义 ID。
	AckId string `protobuf:"bytes,1,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	// ack_type 是确认类型，例如 rule_changed、drain、error。
	AckType string `protobuf:"bytes,2,opt,name=ack_type,json=ackType,proto3" json:"ack_type,omitempty"`
	// revision 是客户端确认时已经处理到的规则水位。
	Revision string `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// message 是可选说明文本，主要用于诊断。
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAck) Reset() {
	*x = ClientAck{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAck) ProtoMessage() {}

func (x *ClientAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAck.ProtoReflect.Descriptor instead.
func (*ClientAck) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{11}
}

func (x *ClientAck) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

func (x *ClientAck) GetAckType() string {
	if x != nil {
		return x.AckType
	}
	return ""
}

func (x *ClientAck) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ClientAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ServerDrain 是服务端要求客户端迁移连接的通知。
type ServerDrain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reason 是 drain 原因，例如 shutdown、rebalance、overloaded。
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// deadline_unix_ms 是客户端应完成迁移的截止时间，Unix 毫秒。
	DeadlineUnixMs int64 `protobuf:"varint,2,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	// preferred_instances 是服务端建议客户端迁移到的目标实例列表。
	PreferredInstances []*PulsarInstance `protobuf:"bytes,3,rep,name=preferred_instances,json=preferredInstances,proto3" json:"preferred_instances,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerDrain) Reset() {
	*x = ServerDrain{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDrain) ProtoMessage() {}

func (x *ServerDrain) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDrain.ProtoReflect.Descriptor instead.
func (*ServerDrain) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{12}
}

func (x *ServerDrain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ServerDrain) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *ServerDrain) GetPreferredInstances() []*PulsarInstance {
	if x != nil {
		return x.PreferredInstances
	}
	return nil
}

// ServerError 是服务端在长连接内返回的错误信息。
type ServerError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code 是稳定的机器可读错误码。
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// message 是面向日志和诊断的错误说明。
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// retry_after_ms 是建议客户端重试等待时间，单位毫秒。
	RetryAfterMs  int64 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerError) Reset() {
	*x = ServerError{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerError) ProtoMessage() {}

func (x *ServerError) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerError.ProtoReflect.Descriptor instead.
func (*ServerError) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{13}
}

func (x *ServerError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerError) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

// AcquireQuotaRequest 是客户端获取限流配额的请求。
type AcquireQuotaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id 是客户端生成的请求 ID，用于日志追踪和排障。
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// application_code 是当前业务应用编码。
	ApplicationCode string `protobuf:"bytes,2,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// client_id 是客户端进程或 SDK 实例 ID。
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// rule_id 是客户端本地命中的限流规则 ID。
	RuleId string `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// quota_key 是本次配额扣减的限流维度 key。
	// 推荐由租户、接口、用户、资源等业务维度稳定拼接生成。
	QuotaKey string `protobuf:"bytes,5,opt,name=quota_key,json=quotaKey,proto3" json:"quota_key,omitempty"`
	// cost 是本次请求消耗的配额数量，必须大于 0。
	// 未设置时服务端可按 1 处理。
	Cost int64 `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	// rule_revision 是客户端本地规则版本。
	// 服务端会与内存规则版本比较，判断客户端是否落后或服务端是否滞后。
	RuleRevision string `protobuf:"bytes,7,opt,name=rule_revision,json=ruleRevision,proto3" json:"rule_revision,omitempty"`
	// rule_checksum 是客户端本地规则内容摘要。
	// 服务端会与内存规则 checksum 比较，发现同版本内容冲突。
	RuleChecksum string `protobuf:"bytes,8,opt,name=rule_checksum,json=ruleChecksum,proto3" json:"rule_checksum,omitempty"`
	// attributes 是可选请求属性，例如 route、method、tenant、region。
	// 首版服务端可只透传记录，后续可参与规则条件匹配。
	Attributes map[string]string `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// topology_revision 是客户端用于计算 target_instance_id 的拓扑版本。
	// 它来自 ListInstancesResponse.instance_revision。
	TopologyRevision string `protobuf:"bytes,10,opt,name=topology_revision,json=topologyRevision,proto3" json:"topology_revision,omitempty"`
	// target_instance_id 是客户端基于 shard key 和 topology_revision 计算出的目标 owner。
	// 服务端会二次校验，当前实例不是 owner 时返回 NOT_OWNER。
	TargetInstanceId string `protobuf:"bytes,11,opt,name=target_instance_id,json=targetInstanceId,proto3" json:"target_instance_id,omitempty"`
	// shard_hash 是客户端计算出的 shard hash，可选，用于服务端诊断 SDK hash 实现是否一致。
	ShardHash     string `protobuf:"bytes,12,opt,name=shard_hash,json=shardHash,proto3" json:"shard_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireQuotaRequest) Reset() {
	*x = AcquireQuotaRequest{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireQuotaRequest) ProtoMessage() {}

func (x *AcquireQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireQuotaRequest.ProtoReflect.Descriptor instead.
func (*AcquireQuotaRequest) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{14}
}

func (x *AcquireQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AcquireQuotaRequest) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *AcquireQuotaRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AcquireQuotaRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AcquireQuotaRequest) GetQuotaKey() string {
	if x != nil {
		return x.QuotaKey
	}
	return ""
}

func (x *AcquireQuotaRequest) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *AcquireQuotaRequest) GetRuleRevision() string {
	if x != nil {
		return x.RuleRevision
	}
	return ""
}

func (x *AcquireQuotaRequest) GetRuleChecksum() string {
	if x != nil {
		return x.RuleChecksum
	}
	return ""
}

func (x *AcquireQuotaRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AcquireQuotaRequest) GetTopologyRevision() string {
	if x != nil {
		return x.TopologyRevision
	}
	return ""
}

func (x *AcquireQuotaRequest) GetTargetInstanceId() string {
	if x != nil {
		return x.TargetInstanceId
	}
	return ""
}

func (x *AcquireQuotaRequest) GetShardHash() string {
	if x != nil {
		return x.ShardHash
	}
	return ""
}

// AcquireQuotaResponse 是服务端配额判定结果。
type AcquireQuotaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id 原样返回客户端请求 ID。
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// decision 是配额判定结果。
	// 只有 ALLOWED 表示扣减成功；DENIED 表示规则一致但配额不足；
	// RULE_STALE、SERVER_RULE_LAG、RULE_CONFLICT、RULE_NOT_FOUND 都表示规则状态问题。
	Decision QuotaDecision `protobuf:"varint,2,opt,name=decision,proto3,enum=stellpulsar.v1.QuotaDecision" json:"decision,omitempty"`
	// rule_id 是服务端参与判定的规则 ID。
	RuleId string `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// rule_revision 是服务端当前规则版本。
	RuleRevision string `protobuf:"bytes,4,opt,name=rule_revision,json=ruleRevision,proto3" json:"rule_revision,omitempty"`
	// rule_checksum 是服务端当前规则 checksum。
	RuleChecksum string `protobuf:"bytes,5,opt,name=rule_checksum,json=ruleChecksum,proto3" json:"rule_checksum,omitempty"`
	// remaining 是本地窗口内剩余配额。
	Remaining int64 `protobuf:"varint,6,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// reset_at_unix_ms 是当前配额窗口重置时间，Unix 毫秒。
	ResetAtUnixMs int64 `protobuf:"varint,7,opt,name=reset_at_unix_ms,json=resetAtUnixMs,proto3" json:"reset_at_unix_ms,omitempty"`
	// retry_after_ms 是建议客户端等待多久后重试，单位毫秒。
	// 常用于 DENIED 或 SERVER_RULE_LAG。
	RetryAfterMs int64 `protobuf:"varint,8,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	// reason 是稳定的诊断原因，例如 allowed、rate_limited、rule_checksum_conflict。
	Reason string `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	// topology_revision 是服务端当前接受的拓扑版本。
	// 客户端收到 NOT_OWNER 或 SHARD_MIGRATING 时应使用该值刷新本地拓扑。
	TopologyRevision string `protobuf:"bytes,10,opt,name=topology_revision,json=topologyRevision,proto3" json:"topology_revision,omitempty"`
	// owner_instance 是服务端计算出的 shard owner。
	// 当 decision 为 NOT_OWNER 时，客户端应优先重试该实例。
	OwnerInstance *PulsarInstance `protobuf:"bytes,11,opt,name=owner_instance,json=ownerInstance,proto3" json:"owner_instance,omitempty"`
	// hash_algorithm 是服务端使用的 owner 计算算法。
	HashAlgorithm string `protobuf:"bytes,12,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireQuotaResponse) Reset() {
	*x = AcquireQuotaResponse{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireQuotaResponse) ProtoMessage() {}

func (x *AcquireQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireQuotaResponse.ProtoReflect.Descriptor instead.
func (*AcquireQuotaResponse) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{15}
}

func (x *AcquireQuotaResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AcquireQuotaResponse) GetDecision() QuotaDecision {
	if x != nil {
		return x.Decision
	}
	return QuotaDecision_QUOTA_DECISION_UNSPECIFIED
}

func (x *AcquireQuotaResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AcquireQuotaResponse) GetRuleRevision() string {
	if x != nil {
		return x.RuleRevision
	}
	return ""
}

func (x *AcquireQuotaResponse) GetRuleChecksum() string {
	if x != nil {
		return x.RuleChecksum
	}
	return ""
}

func (x *AcquireQuotaResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *AcquireQuotaResponse) GetResetAtUnixMs() int64 {
	if x != nil {
		return x.ResetAtUnixMs
	}
	return 0
}

func (x *AcquireQuotaResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *AcquireQuotaResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AcquireQuotaResponse) GetTopologyRevision() string {
	if x != nil {
		return x.TopologyRevision
	}
	return ""
}

func (x *AcquireQuotaResponse) GetOwnerInstance() *PulsarInstance {
	if x != nil {
		return x.OwnerInstance
	}
	return nil
}

func (x *AcquireQuotaResponse) GetHashAlgorithm() string {
	if x != nil {
		return x.HashAlgorithm
	}
	return ""
}

// GetRuleSnapshotRequest 是客户端拉取服务端规则快照的请求。
type GetRuleSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application_code 是要查询的应用编码。
	ApplicationCode string `protobuf:"bytes,1,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// rule_ids 是可选规则 ID 列表。
	// 为空时返回该应用下服务端当前持有的全部限流规则。
	RuleIds []string `protobuf:"bytes,2,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	// known_revision 是客户端已知规则水位。
	// 服务端首版可忽略，后续可用于无变化快速返回。
	KnownRevision string `protobuf:"bytes,3,opt,name=known_revision,json=knownRevision,proto3" json:"known_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSnapshotRequest) Reset() {
	*x = GetRuleSnapshotRequest{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSnapshotRequest) ProtoMessage() {}

func (x *GetRuleSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetRuleSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{16}
}

func (x *GetRuleSnapshotRequest) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *GetRuleSnapshotRequest) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

func (x *GetRuleSnapshotRequest) GetKnownRevision() string {
	if x != nil {
		return x.KnownRevision
	}
	return ""
}

// GetRuleSnapshotResponse 是服务端返回的规则快照。
type GetRuleSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application_code 是响应对应的应用编码。
	ApplicationCode string `protobuf:"bytes,1,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// revision 是服务端全局规则水位。
	Revision string `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// checksum 是服务端全局规则 checksum。
	Checksum string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// rules 是本次返回的限流规则列表。
	Rules         []*RateLimitRule `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSnapshotResponse) Reset() {
	*x = GetRuleSnapshotResponse{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSnapshotResponse) ProtoMessage() {}

func (x *GetRuleSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetRuleSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{17}
}

func (x *GetRuleSnapshotResponse) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *GetRuleSnapshotResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GetRuleSnapshotResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *GetRuleSnapshotResponse) GetRules() []*RateLimitRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// ValidateRuleSnapshotRequest 是客户端校验规则 digest 的请求。
type ValidateRuleSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application_code 是当前业务应用编码。
	ApplicationCode string `protobuf:"bytes,1,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// rule_digests 是客户端当前持有的规则摘要集合。
	RuleDigests   []*RuleDigest `protobuf:"bytes,2,rep,name=rule_digests,json=ruleDigests,proto3" json:"rule_digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleSnapshotRequest) Reset() {
	*x = ValidateRuleSnapshotRequest{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleSnapshotRequest) ProtoMessage() {}

func (x *ValidateRuleSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ValidateRuleSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateRuleSnapshotRequest) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *ValidateRuleSnapshotRequest) GetRuleDigests() []*RuleDigest {
	if x != nil {
		return x.RuleDigests
	}
	return nil
}

// ValidateRuleSnapshotResponse 是规则 digest 校验结果。
type ValidateRuleSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application_code 是响应对应的应用编码。
	ApplicationCode string `protobuf:"bytes,1,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// status 是整体校验状态。
	// 如果任一规则冲突，整体状态应为 CONFLICT；如果任一规则缺失，整体状态可为 NOT_FOUND。
	Status RuleValidationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=stellpulsar.v1.RuleValidationStatus" json:"status,omitempty"`
	// results 是每条规则 digest 的明细校验结果。
	Results       []*RuleValidationResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRuleSnapshotResponse) Reset() {
	*x = ValidateRuleSnapshotResponse{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRuleSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleSnapshotResponse) ProtoMessage() {}

func (x *ValidateRuleSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ValidateRuleSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateRuleSnapshotResponse) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *ValidateRuleSnapshotResponse) GetStatus() RuleValidationStatus {
	if x != nil {
		return x.Status
	}
	return RuleValidationStatus_RULE_VALIDATION_STATUS_UNSPECIFIED
}

func (x *ValidateRuleSnapshotResponse) GetResults() []*RuleValidationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// RuleDigest 是规则轻量摘要，用于版本比较和冲突判断。
type RuleDigest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application_code 是规则所属应用编码。
	ApplicationCode string `protobuf:"bytes,1,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// rule_id 是限流规则 ID。
	RuleId string `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// revision 是规则版本，通常来自 StellOrbit snapshotVersion。
	Revision string `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// checksum 是规则内容摘要。
	Checksum string `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// schema_version 是规则内容 schema 版本。
	SchemaVersion string `protobuf:"bytes,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleDigest) Reset() {
	*x = RuleDigest{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleDigest) ProtoMessage() {}

func (x *RuleDigest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleDigest.ProtoReflect.Descriptor instead.
func (*RuleDigest) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{20}
}

func (x *RuleDigest) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *RuleDigest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleDigest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *RuleDigest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RuleDigest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

// RuleValidationResult 是单条规则 digest 的校验明细。
type RuleValidationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_digest 是客户端提交的规则摘要。
	ClientDigest *RuleDigest `protobuf:"bytes,1,opt,name=client_digest,json=clientDigest,proto3" json:"client_digest,omitempty"`
	// server_digest 是服务端当前规则摘要。
	// 如果服务端不存在该规则，该字段可以为空。
	ServerDigest *RuleDigest `protobuf:"bytes,2,opt,name=server_digest,json=serverDigest,proto3" json:"server_digest,omitempty"`
	// status 是该规则的校验状态。
	Status RuleValidationStatus `protobuf:"varint,3,opt,name=status,proto3,enum=stellpulsar.v1.RuleValidationStatus" json:"status,omitempty"`
	// message 是诊断说明，例如 matched、client_rule_stale、rule_checksum_conflict。
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleValidationResult) Reset() {
	*x = RuleValidationResult{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleValidationResult) ProtoMessage() {}

func (x *RuleValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleValidationResult.ProtoReflect.Descriptor instead.
func (*RuleValidationResult) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{21}
}

func (x *RuleValidationResult) GetClientDigest() *RuleDigest {
	if x != nil {
		return x.ClientDigest
	}
	return nil
}

func (x *RuleValidationResult) GetServerDigest() *RuleDigest {
	if x != nil {
		return x.ServerDigest
	}
	return nil
}

func (x *RuleValidationResult) GetStatus() RuleValidationStatus {
	if x != nil {
		return x.Status
	}
	return RuleValidationStatus_RULE_VALIDATION_STATUS_UNSPECIFIED
}

func (x *RuleValidationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RateLimitRule 是服务端暴露给客户端的限流规则运行时视图。
//
// 它不是 StellOrbit 原始发布 payload 的完整替代品，
// 只承载客户端与 StellPulsar 服务端交互所需的核心运行时字段。
type RateLimitRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application_code 是规则所属应用编码。
	ApplicationCode string `protobuf:"bytes,1,opt,name=application_code,json=applicationCode,proto3" json:"application_code,omitempty"`
	// rule_id 是限流规则 ID。
	RuleId string `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// name 是规则名称。
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// revision 是规则版本，通常来自 StellOrbit snapshotVersion。
	Revision string `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	// checksum 是规则内容摘要。
	Checksum string `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// schema_version 是规则内容 schema 版本。
	SchemaVersion string `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// algorithm 是限流算法，例如 fixed_window、token_bucket、sliding_window。
	Algorithm string `protobuf:"bytes,7,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// quota 是每个窗口允许的配额数量。
	Quota int64 `protobuf:"varint,8,opt,name=quota,proto3" json:"quota,omitempty"`
	// window_seconds 是配额窗口长度，单位秒。
	WindowSeconds int64 `protobuf:"varint,9,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	// burst 是允许的突发配额。
	// 对不支持突发的算法可为 0。
	Burst int64 `protobuf:"varint,10,opt,name=burst,proto3" json:"burst,omitempty"`
	// dimensions 是规则匹配和配额 key 组成维度，例如 tenant、route、method。
	Dimensions []string `protobuf:"bytes,11,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	// fail_policy 是规则异常时客户端或服务端的降级策略，例如 fail_open、fail_closed。
	FailPolicy string `protobuf:"bytes,12,opt,name=fail_policy,json=failPolicy,proto3" json:"fail_policy,omitempty"`
	// attributes 是扩展属性，用于承载策略标签或后续兼容字段。
	Attributes    map[string]string `protobuf:"bytes,13,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRule) Reset() {
	*x = RateLimitRule{}
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRule) ProtoMessage() {}

func (x *RateLimitRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRule.ProtoReflect.Descriptor instead.
func (*RateLimitRule) Descriptor() ([]byte, []int) {
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP(), []int{22}
}

func (x *RateLimitRule) GetApplicationCode() string {
	if x != nil {
		return x.ApplicationCode
	}
	return ""
}

func (x *RateLimitRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RateLimitRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RateLimitRule) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *RateLimitRule) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RateLimitRule) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RateLimitRule) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RateLimitRule) GetQuota() int64 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *RateLimitRule) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *RateLimitRule) GetBurst() int64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimitRule) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *RateLimitRule) GetFailPolicy() string {
	if x != nil {
		return x.FailPolicy
	}
	return ""
}

func (x *RateLimitRule) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_api_stellpulsar_v1_stellpulsar_proto protoreflect.FileDescriptor

const file_api_stellpulsar_v1_stellpulsar_proto_rawDesc = "" +
	"\n" +
	"$api/stellpulsar/v1/stellpulsar.proto\x12\x0estellpulsar.v1\"\xc1\x02\n" +
	"\x14ListInstancesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12)\n" +
	"\x10application_code\x18\x02 \x01(\tR\x0fapplicationCode\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12>\n" +
	"\x1bsupported_protocol_versions\x18\x04 \x03(\tR\x19supportedProtocolVersions\x12H\n" +
	"\x06labels\x18\x05 \x03(\v20.stellpulsar.v1.ListInstancesRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\x15ListInstancesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12+\n" +
	"\x11instance_revision\x18\x02 \x01(\tR\x10instanceRevision\x12+\n" +
	"\x12expires_at_unix_ms\x18\x03 \x01(\x03R\x0fexpiresAtUnixMs\x12<\n" +
	"\tinstances\x18\x04 \x03(\v2\x1e.stellpulsar.v1.PulsarInstanceR\tinstances\x12%\n" +
	"\x0ehash_algorithm\x18\x05 \x01(\tR\rhashAlgorithm\"\xfd\x02\n" +
	"\x0ePulsarInstance\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04zone\x18\x06 \x01(\tR\x04zone\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12#\n" +
	"\rrule_revision\x18\b \x01(\tR\fruleRevision\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12H\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2,.stellpulsar.v1.PulsarInstance.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe9\x02\n" +
	"\vClientFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12)\n" +
	"\x10application_code\x18\x03 \x01(\tR\x0fapplicationCode\x123\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x1b.stellpulsar.v1.ClientHelloH\x00R\x05hello\x12?\n" +
	"\theartbeat\x18\v \x01(\v2\x1f.stellpulsar.v1.ClientHeartbeatH\x00R\theartbeat\x12C\n" +
	"\vrule_digest\x18\f \x01(\v2 .stellpulsar.v1.ClientRuleDigestH\x00R\n" +
	"ruleDigest\x12-\n" +
	"\x03ack\x18\r \x01(\v2\x19.stellpulsar.v1.ClientAckH\x00R\x03ackB\t\n" +
	"\apayload\"\x8d\x03\n" +
	"\vServerFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x12server_instance_id\x18\x02 \x01(\tR\x10serverInstanceId\x123\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x1b.stellpulsar.v1.ServerHelloH\x00R\x05hello\x12?\n" +
	"\theartbeat\x18\v \x01(\v2\x1f.stellpulsar.v1.ServerHeartbeatH\x00R\theartbeat\x12F\n" +
	"\frule_changed\x18\f \x01(\v2!.stellpulsar.v1.ServerRuleChangedH\x00R\vruleChanged\x123\n" +
	"\x05drain\x18\r \x01(\v2\x1b.stellpulsar.v1.ServerDrainH\x00R\x05drain\x123\n" +
	"\x05error\x18\x0e \x01(\v2\x1b.stellpulsar.v1.ServerErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x92\x02\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12)\n" +
	"\x10application_code\x18\x03 \x01(\tR\x0fapplicationCode\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x120\n" +
	"\x14selected_instance_id\x18\x05 \x01(\tR\x12selectedInstanceId\x12=\n" +
	"\frule_digests\x18\x06 \x03(\v2\x1a.stellpulsar.v1.RuleDigestR\vruleDigests\"\x8b\x02\n" +
	"\vServerHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12,\n" +
	"\x12server_instance_id\x18\x02 \x01(\tR\x10serverInstanceId\x120\n" +
	"\x14global_rule_revision\x18\x03 \x01(\tR\x12globalRuleRevision\x12=\n" +
	"\frule_digests\x18\x04 \x03(\v2\x1a.stellpulsar.v1.RuleDigestR\vruleDigests\x122\n" +
	"\x15heartbeat_interval_ms\x18\x05 \x01(\x03R\x13heartbeatIntervalMs\"|\n" +
	"\x0fClientHeartbeat\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x01 \x01(\x03R\fsentAtUnixMs\x12B\n" +
	"\x1elast_seen_server_rule_revision\x18\x02 \x01(\tR\x1alastSeenServerRuleRevision\"j\n" +
	"\x0fServerHeartbeat\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x01 \x01(\x03R\fsentAtUnixMs\x120\n" +
	"\x14global_rule_revision\x18\x02 \x01(\tR\x12globalRuleRevision\"Q\n" +
	"\x10ClientRuleDigest\x12=\n" +
	"\frule_digests\x18\x01 \x03(\v2\x1a.stellpulsar.v1.RuleDigestR\vruleDigests\"\xbc\x01\n" +
	"\x11ServerRuleChanged\x120\n" +
	"\x14global_rule_revision\x18\x01 \x01(\tR\x12globalRuleRevision\x12?\n" +
	"\rchanged_rules\x18\x02 \x03(\v2\x1a.stellpulsar.v1.RuleDigestR\fchangedRules\x124\n" +
	"\x16requires_client_resync\x18\x03 \x01(\bR\x14requiresClientResync\"s\n" +
	"\tClientAck\x12\x15\n" +
	"\x06ack_id\x18\x01 \x01(\tR\x05ackId\x12\x19\n" +
	"\back_type\x18\x02 \x01(\tR\aackType\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xa0\x01\n" +
	"\vServerDrain\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12(\n" +
	"\x10deadline_unix_ms\x18\x02 \x01(\x03R\x0edeadlineUnixMs\x12O\n" +
	"\x13preferred_instances\x18\x03 \x03(\v2\x1e.stellpulsar.v1.PulsarInstanceR\x12preferredInstances\"a\n" +
	"\vServerError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs\"\x9e\x04\n" +
	"\x13AcquireQuotaRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x10application_code\x18\x02 \x01(\tR\x0fapplicationCode\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\tquota_key\x18\x05 \x01(\tR\bquotaKey\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x03R\x04cost\x12#\n" +
	"\rrule_revision\x18\a \x01(\tR\fruleRevision\x12#\n" +
	"\rrule_checksum\x18\b \x01(\tR\fruleChecksum\x12S\n" +
	"\n" +
	"attributes\x18\t \x03(\v23.stellpulsar.v1.AcquireQuotaRequest.AttributesEntryR\n" +
	"attributes\x12+\n" +
	"\x11topology_revision\x18\n" +
	" \x01(\tR\x10topologyRevision\x12,\n" +
	"\x12target_instance_id\x18\v \x01(\tR\x10targetInstanceId\x12\x1d\n" +
	"\n" +
	"shard_hash\x18\f \x01(\tR\tshardHash\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x03\n" +
	"\x14AcquireQuotaResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x1d.stellpulsar.v1.QuotaDecisionR\bdecision\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12#\n" +
	"\rrule_revision\x18\x04 \x01(\tR\fruleRevision\x12#\n" +
	"\rrule_checksum\x18\x05 \x01(\tR\fruleChecksum\x12\x1c\n" +
	"\tremaining\x18\x06 \x01(\x03R\tremaining\x12'\n" +
	"\x10reset_at_unix_ms\x18\a \x01(\x03R\rresetAtUnixMs\x12$\n" +
	"\x0eretry_after_ms\x18\b \x01(\x03R\fretryAfterMs\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12+\n" +
	"\x11topology_revision\x18\n" +
	" \x01(\tR\x10topologyRevision\x12E\n" +
	"\x0eowner_instance\x18\v \x01(\v2\x1e.stellpulsar.v1.PulsarInstanceR\rownerInstance\x12%\n" +
	"\x0ehash_algorithm\x18\f \x01(\tR\rhashAlgorithm\"\x85\x01\n" +
	"\x16GetRuleSnapshotRequest\x12)\n" +
	"\x10application_code\x18\x01 \x01(\tR\x0fapplicationCode\x12\x19\n" +
	"\brule_ids\x18\x02 \x03(\tR\aruleIds\x12%\n" +
	"\x0eknown_revision\x18\x03 \x01(\tR\rknownRevision\"\xb1\x01\n" +
	"\x17GetRuleSnapshotResponse\x12)\n" +
	"\x10application_code\x18\x01 \x01(\tR\x0fapplicationCode\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x123\n" +
	"\x05rules\x18\x04 \x03(\v2\x1d.stellpulsar.v1.RateLimitRuleR\x05rules\"\x87\x01\n" +
	"\x1bValidateRuleSnapshotRequest\x12)\n" +
	"\x10application_code\x18\x01 \x01(\tR\x0fapplicationCode\x12=\n" +
	"\frule_digests\x18\x02 \x03(\v2\x1a.stellpulsar.v1.RuleDigestR\vruleDigests\"\xc7\x01\n" +
	"\x1cValidateRuleSnapshotResponse\x12)\n" +
	"\x10application_code\x18\x01 \x01(\tR\x0fapplicationCode\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.stellpulsar.v1.RuleValidationStatusR\x06status\x12>\n" +
	"\aresults\x18\x03 \x03(\v2$.stellpulsar.v1.RuleValidationResultR\aresults\"\xaf\x01\n" +
	"\n" +
	"RuleDigest\x12)\n" +
	"\x10application_code\x18\x01 \x01(\tR\x0fapplicationCode\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\tR\rschemaVersion\"\xf0\x01\n" +
	"\x14RuleValidationResult\x12?\n" +
	"\rclient_digest\x18\x01 \x01(\v2\x1a.stellpulsar.v1.RuleDigestR\fclientDigest\x12?\n" +
	"\rserver_digest\x18\x02 \x01(\v2\x1a.stellpulsar.v1.RuleDigestR\fserverDigest\x12<\n" +
	"\x06status\x18\x03 \x01(\x0e2$.stellpulsar.v1.RuleValidationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x86\x04\n" +
	"\rRateLimitRule\x12)\n" +
	"\x10application_code\x18\x01 \x01(\tR\x0fapplicationCode\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\tR\brevision\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x12\x1c\n" +
	"\talgorithm\x18\a \x01(\tR\talgorithm\x12\x14\n" +
	"\x05quota\x18\b \x01(\x03R\x05quota\x12%\n" +
	"\x0ewindow_seconds\x18\t \x01(\x03R\rwindowSeconds\x12\x14\n" +
	"\x05burst\x18\n" +
	" \x01(\x03R\x05burst\x12\x1e\n" +
	"\n" +
	"dimensions\x18\v \x03(\tR\n" +
	"dimensions\x12\x1f\n" +
	"\vfail_policy\x18\f \x01(\tR\n" +
	"failPolicy\x12M\n" +
	"\n" +
	"attributes\x18\r \x03(\v2-.stellpulsar.v1.RateLimitRule.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd4\x02\n" +
	"\rQuotaDecision\x12\x1e\n" +
	"\x1aQUOTA_DECISION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16QUOTA_DECISION_ALLOWED\x10\x01\x12\x19\n" +
	"\x15QUOTA_DECISION_DENIED\x10\x02\x12\x1d\n" +
	"\x19QUOTA_DECISION_RULE_STALE\x10\x03\x12\"\n" +
	"\x1eQUOTA_DECISION_SERVER_RULE_LAG\x10\x04\x12 \n" +
	"\x1cQUOTA_DECISION_RULE_CONFLICT\x10\x05\x12!\n" +
	"\x1dQUOTA_DECISION_RULE_NOT_FOUND\x10\x06\x12\"\n" +
	"\x1eQUOTA_DECISION_INVALID_REQUEST\x10\a\x12\x1c\n" +
	"\x18QUOTA_DECISION_NOT_OWNER\x10\b\x12\"\n" +
	"\x1eQUOTA_DECISION_SHARD_MIGRATING\x10\t*\xff\x01\n" +
	"\x14RuleValidationStatus\x12&\n" +
	"\"RULE_VALIDATION_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRULE_VALIDATION_STATUS_MATCHED\x10\x01\x12'\n" +
	"#RULE_VALIDATION_STATUS_CLIENT_STALE\x10\x02\x12'\n" +
	"#RULE_VALIDATION_STATUS_SERVER_STALE\x10\x03\x12#\n" +
	"\x1fRULE_VALIDATION_STATUS_CONFLICT\x10\x04\x12$\n" +
	" RULE_VALIDATION_STATUS_NOT_FOUND\x10\x052{\n" +
	"\x1bStellPulsarDiscoveryService\x12\\\n" +
	"\rListInstances\x12$.stellpulsar.v1.ListInstancesRequest\x1a%.stellpulsar.v1.ListInstancesResponse2\x9a\x03\n" +
	"\x19StellPulsarRuntimeService\x12K\n" +
	"\vOpenSession\x12\x1b.stellpulsar.v1.ClientFrame\x1a\x1b.stellpulsar.v1.ServerFrame(\x010\x01\x12Y\n" +
	"\fAcquireQuota\x12#.stellpulsar.v1.AcquireQuotaRequest\x1a$.stellpulsar.v1.AcquireQuotaResponse\x12b\n" +
	"\x0fGetRuleSnapshot\x12&.stellpulsar.v1.GetRuleSnapshotRequest\x1a'.stellpulsar.v1.GetRuleSnapshotResponse\x12q\n" +
	"\x14ValidateRuleSnapshot\x12+.stellpulsar.v1.ValidateRuleSnapshotRequest\x1a,.stellpulsar.v1.ValidateRuleSnapshotResponseBJZHgithub.com/stellhub/stellpulsar-service/api/stellpulsar/v1;stellpulsarv1b\x06proto3"

var (
	file_api_stellpulsar_v1_stellpulsar_proto_rawDescOnce sync.Once
	file_api_stellpulsar_v1_stellpulsar_proto_rawDescData []byte
)

func file_api_stellpulsar_v1_stellpulsar_proto_rawDescGZIP() []byte {
	file_api_stellpulsar_v1_stellpulsar_proto_rawDescOnce.Do(func() {
		file_api_stellpulsar_v1_stellpulsar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stellpulsar_v1_stellpulsar_proto_rawDesc), len(file_api_stellpulsar_v1_stellpulsar_proto_rawDesc)))
	})
	return file_api_stellpulsar_v1_stellpulsar_proto_rawDescData
}

var file_api_stellpulsar_v1_stellpulsar_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_stellpulsar_v1_stellpulsar_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_stellpulsar_v1_stellpulsar_proto_goTypes = []any{
	(QuotaDecision)(0),                   // 0: stellpulsar.v1.QuotaDecision
	(RuleValidationStatus)(0),            // 1: stellpulsar.v1.RuleValidationStatus
	(*ListInstancesRequest)(nil),         // 2: stellpulsar.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil),        // 3: stellpulsar.v1.ListInstancesResponse
	(*PulsarInstance)(nil),               // 4: stellpulsar.v1.PulsarInstance
	(*ClientFrame)(nil),                  // 5: stellpulsar.v1.ClientFrame
	(*ServerFrame)(nil),                  // 6: stellpulsar.v1.ServerFrame
	(*ClientHello)(nil),                  // 7: stellpulsar.v1.ClientHello
	(*ServerHello)(nil),                  // 8: stellpulsar.v1.ServerHello
	(*ClientHeartbeat)(nil),              // 9: stellpulsar.v1.ClientHeartbeat
	(*ServerHeartbeat)(nil),              // 10: stellpulsar.v1.ServerHeartbeat
	(*ClientRuleDigest)(nil),             // 11: stellpulsar.v1.ClientRuleDigest
	(*ServerRuleChanged)(nil),            // 12: stellpulsar.v1.ServerRuleChanged
	(*ClientAck)(nil),                    // 13: stellpulsar.v1.ClientAck
	(*ServerDrain)(nil),                  // 14: stellpulsar.v1.ServerDrain
	(*ServerError)(nil),                  // 15: stellpulsar.v1.ServerError
	(*AcquireQuotaRequest)(nil),          // 16: stellpulsar.v1.AcquireQuotaRequest
	(*AcquireQuotaResponse)(nil),         // 17: stellpulsar.v1.AcquireQuotaResponse
	(*GetRuleSnapshotRequest)(nil),       // 18: stellpulsar.v1.GetRuleSnapshotRequest
	(*GetRuleSnapshotResponse)(nil),      // 19: stellpulsar.v1.GetRuleSnapshotResponse
	(*ValidateRuleSnapshotRequest)(nil),  // 20: stellpulsar.v1.ValidateRuleSnapshotRequest
	(*ValidateRuleSnapshotResponse)(nil), // 21: stellpulsar.v1.ValidateRuleSnapshotResponse
	(*RuleDigest)(nil),                   // 22: stellpulsar.v1.RuleDigest
	(*RuleValidationResult)(nil),         // 23: stellpulsar.v1.RuleValidationResult
	(*RateLimitRule)(nil),                // 24: stellpulsar.v1.RateLimitRule
	nil,                                  // 25: stellpulsar.v1.ListInstancesRequest.LabelsEntry
	nil,                                  // 26: stellpulsar.v1.PulsarInstance.MetadataEntry
	nil,                                  // 27: stellpulsar.v1.AcquireQuotaRequest.AttributesEntry
	nil,                                  // 28: stellpulsar.v1.RateLimitRule.AttributesEntry
}
var file_api_stellpulsar_v1_stellpulsar_proto_depIdxs = []int32{
	25, // 0: stellpulsar.v1.ListInstancesRequest.labels:type_name -> stellpulsar.v1.ListInstancesRequest.LabelsEntry
	4,  // 1: stellpulsar.v1.ListInstancesResponse.instances:type_name -> stellpulsar.v1.PulsarInstance
	26, // 2: stellpulsar.v1.PulsarInstance.metadata:type_name -> stellpulsar.v1.PulsarInstance.MetadataEntry
	7,  // 3: stellpulsar.v1.ClientFrame.hello:type_name -> stellpulsar.v1.ClientHello
	9,  // 4: stellpulsar.v1.ClientFrame.heartbeat:type_name -> stellpulsar.v1.ClientHeartbeat
	11, // 5: stellpulsar.v1.ClientFrame.rule_digest:type_name -> stellpulsar.v1.ClientRuleDigest
	13, // 6: stellpulsar.v1.ClientFrame.ack:type_name -> stellpulsar.v1.ClientAck
	8,  // 7: stellpulsar.v1.ServerFrame.hello:type_name -> stellpulsar.v1.ServerHello
	10, // 8: stellpulsar.v1.ServerFrame.heartbeat:type_name -> stellpulsar.v1.ServerHeartbeat
	12, // 9: stellpulsar.v1.ServerFrame.rule_changed:type_name -> stellpulsar.v1.ServerRuleChanged
	14, // 10: stellpulsar.v1.ServerFrame.drain:type_name -> stellpulsar.v1.ServerDrain
	15, // 11: stellpulsar.v1.ServerFrame.error:type_name -> stellpulsar.v1.ServerError
	22, // 12: stellpulsar.v1.ClientHello.rule_digests:type_name -> stellpulsar.v1.RuleDigest
	22, // 13: stellpulsar.v1.ServerHello.rule_digests:type_name -> stellpulsar.v1.RuleDigest
	22, // 14: stellpulsar.v1.ClientRuleDigest.rule_digests:type_name -> stellpulsar.v1.RuleDigest
	22, // 15: stellpulsar.v1.ServerRuleChanged.changed_rules:type_name -> stellpulsar.v1.RuleDigest
	4,  // 16: stellpulsar.v1.ServerDrain.preferred_instances:type_name -> stellpulsar.v1.PulsarInstance
	27, // 17: stellpulsar.v1.AcquireQuotaRequest.attributes:type_name -> stellpulsar.v1.AcquireQuotaRequest.AttributesEntry
	0,  // 18: stellpulsar.v1.AcquireQuotaResponse.decision:type_name -> stellpulsar.v1.QuotaDecision
	4,  // 19: stellpulsar.v1.AcquireQuotaResponse.owner_instance:type_name -> stellpulsar.v1.PulsarInstance
	24, // 20: stellpulsar.v1.GetRuleSnapshotResponse.rules:type_name -> stellpulsar.v1.RateLimitRule
	22, // 21: stellpulsar.v1.ValidateRuleSnapshotRequest.rule_digests:type_name -> stellpulsar.v1.RuleDigest
	1,  // 22: stellpulsar.v1.ValidateRuleSnapshotResponse.status:type_name -> stellpulsar.v1.RuleValidationStatus
	23, // 23: stellpulsar.v1.ValidateRuleSnapshotResponse.results:type_name -> stellpulsar.v1.RuleValidationResult
	22, // 24: stellpulsar.v1.RuleValidationResult.client_digest:type_name -> stellpulsar.v1.RuleDigest
	22, // 25: stellpulsar.v1.RuleValidationResult.server_digest:type_name -> stellpulsar.v1.RuleDigest
	1,  // 26: stellpulsar.v1.RuleValidationResult.status:type_name -> stellpulsar.v1.RuleValidationStatus
	28, // 27: stellpulsar.v1.RateLimitRule.attributes:type_name -> stellpulsar.v1.RateLimitRule.AttributesEntry
	2,  // 28: stellpulsar.v1.StellPulsarDiscoveryService.ListInstances:input_type -> stellpulsar.v1.ListInstancesRequest
	5,  // 29: stellpulsar.v1.StellPulsarRuntimeService.OpenSession:input_type -> stellpulsar.v1.ClientFrame
	16, // 30: stellpulsar.v1.StellPulsarRuntimeService.AcquireQuota:input_type -> stellpulsar.v1.AcquireQuotaRequest
	18, // 31: stellpulsar.v1.StellPulsarRuntimeService.GetRuleSnapshot:input_type -> stellpulsar.v1.GetRuleSnapshotRequest
	20, // 32: stellpulsar.v1.StellPulsarRuntimeService.ValidateRuleSnapshot:input_type -> stellpulsar.v1.ValidateRuleSnapshotRequest
	3,  // 33: stellpulsar.v1.StellPulsarDiscoveryService.ListInstances:output_type -> stellpulsar.v1.ListInstancesResponse
	6,  // 34: stellpulsar.v1.StellPulsarRuntimeService.OpenSession:output_type -> stellpulsar.v1.ServerFrame
	17, // 35: stellpulsar.v1.StellPulsarRuntimeService.AcquireQuota:output_type -> stellpulsar.v1.AcquireQuotaResponse
	19, // 36: stellpulsar.v1.StellPulsarRuntimeService.GetRuleSnapshot:output_type -> stellpulsar.v1.GetRuleSnapshotResponse
	21, // 37: stellpulsar.v1.StellPulsarRuntimeService.ValidateRuleSnapshot:output_type -> stellpulsar.v1.ValidateRuleSnapshotResponse
	33, // [33:38] is the sub-list for method output_type
	28, // [28:33] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_api_stellpulsar_v1_stellpulsar_proto_init() }
func file_api_stellpulsar_v1_stellpulsar_proto_init() {
	if File_api_stellpulsar_v1_stellpulsar_proto != nil {
		return
	}
	file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Heartbeat)(nil),
		(*ClientFrame_RuleDigest)(nil),
		(*ClientFrame_Ack)(nil),
	}
	file_api_stellpulsar_v1_stellpulsar_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerFrame_Hello)(nil),
		(*ServerFrame_Heartbeat)(nil),
		(*ServerFrame_RuleChanged)(nil),
		(*ServerFrame_Drain)(nil),
		(*ServerFrame_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stellpulsar_v1_stellpulsar_proto_rawDesc), len(file_api_stellpulsar_v1_stellpulsar_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_stellpulsar_v1_stellpulsar_proto_goTypes,
		DependencyIndexes: file_api_stellpulsar_v1_stellpulsar_proto_depIdxs,
		EnumInfos:         file_api_stellpulsar_v1_stellpulsar_proto_enumTypes,
		MessageInfos:      file_api_stellpulsar_v1_stellpulsar_proto_msgTypes,
	}.Build()
	File_api_stellpulsar_v1_stellpulsar_proto = out.File
	file_api_stellpulsar_v1_stellpulsar_proto_goTypes = nil
	file_api_stellpulsar_v1_stellpulsar_proto_depIdxs = nil
}
